### PR TITLE
Update bootloader to use Tock

### PR DESCRIPTION
**Pull request by bradjc**
This leaves in the old bootloader for now, but going to `boards/hail-bootloader` and running `make` should produce a working bootloader made with Tock.

### CODE REVIEW

**Review by brghena — COMMENTED** [review]
The code looks good.

In testing, I got some strange results though. I've got Tockloader 0.9.0, and if I run `tockloader list` multiple times in a row (say five times back to back) with the original bootloader, everything works fine. With the new bootloader though, about 1 in 3 times it hangs until I Ctrl-C it.

Before, I was running Tockloader 0.8.0 and about 1 in 3 times with the new bootloader I received an error response:
```
Error: No response after issuing command
Traceback (most recent call last):
  File "/home/brghena/.local/bin/tockloader", line 11, in <module>
    sys.exit(main())
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/main.py", line 478, in main
    args.func(args)
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/main.py", line 96, in command_list
    tock_loader.list_apps(args.verbose, args.quiet)
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/tockloader.py", line 73, in list_apps
    with self._start_communication_with_board():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/tockloader.py", line 462, in _start_communication_with_board
    raise(e)
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/tockloader.py", line 455, in _start_communication_with_board
    self.channel.determine_current_board()
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/bootloader_serial.py", line 626, in determine_current_board
    attributes = self.get_all_attributes()
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/bootloader_serial.py", line 573, in get_all_attributes
    attributes.append(self.get_attribute(index))
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/bootloader_serial.py", line 562, in get_attribute
    if ret[1] == self.RESPONSE_BADADDR:
IndexError: index out of range
```

**Comment by bradjc** [comment]
Hm ok. I think it hangs for one of two reasons:
1. tockloader is waiting for a `pong` message after sending a `ping` as a part of its initial startup process. It should do this in a loop, but it wouldn't work if say the bootloader had jumped to the kernel rather than stay in bootloader mode.
2. tockloader is waiting for a response from some other command, and for some reason the bootloader didn't receive the command or didnt respond with a response.

When you ctrl-c do you always get a backtrace? If so then I think it is the latter case.

Sounds like there are still some timing issues to be sorted out.

**Comment by brghena** [comment]
When I ctrl-c I do get a backtrace:

```
$ tockloader list 
No device name specified. Using default "tock"
Using "/dev/ttyUSB0 - Hail IoT Module - TockOS"

^CTraceback (most recent call last):
  File "/home/brghena/.local/bin/tockloader", line 11, in <module>
    sys.exit(main())
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/main.py", line 502, in main
    args.func(args)
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/main.py", line 96, in command_list
    tock_loader.list_apps(args.verbose, args.quiet)
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/tockloader.py", line 73, in list_apps
    with self._start_communication_with_board():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/tockloader.py", line 449, in _start_communication_with_board
    self.channel.determine_current_board()
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/bootloader_serial.py", line 648, in determine_current_board
    attributes = self.get_all_attributes()
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/bootloader_serial.py", line 595, in get_all_attributes
    attributes.append(self.get_attribute(index))
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/bootloader_serial.py", line 581, in get_attribute
    success, ret = self._issue_command(self.COMMAND_GET_ATTRIBUTE, message, True, 64, self.RESPONSE_GET_ATTRIBUTE)
  File "/home/brghena/.local/lib/python3.6/site-packages/tockloader/bootloader_serial.py", line 400, in _issue_command
    new_data = self.sp.read(bytes_to_read - len(ret))
  File "/home/brghena/.local/lib/python3.6/site-packages/serial/serialposix.py", line 483, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
KeyboardInterrupt
```

Does this problem occur for you too?

**Comment by bradjc** [comment]
It certainly did will testing, but not in the version in this PR. But yeah what you are seeing is consistent with the bootloader not receiving the command that tockloader sent, and therefore not responding with anything, sending tockloader into a loop.

**Comment by bradjc** [comment]
Merged because why not.

**Pull request merged**
